### ISSUE TITLE
Exception related to hibernate.dialect when running MySQL-Hibernate example

### ISSUE THREAD

**Issue by derek-baker** [netgloo/spring-boot-samples#10]
Below is the initial exception I get when I attempt to run the MySQL-Hibernate example. I'm coming to the Java world from .NET, so any assistance would be greatly appreciated. I attached the console output of my mvn spring-boot:run as a .txt file. 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]:
 Invocation of init method failed; nested exception is org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

[exception.txt](https://github.com/netgloo/spring-boot-samples/files/1122702/exception.txt)

**Comment by azanelli** [comment]
Looks like you have a problem connecting to MySQL. Are you sure MySQL is up and running? Also try to open the `application.properties` file and check if all is correctly configured.

Anyway, for any further problems and/or questions please use [Stackoverflow](https://stackoverflow.com) Thank you. 🙂
