### ISSUE TITLE
"Error creating bean with name" issue

### ISSUE THREAD

**Issue by daverbj** [netgloo/spring-boot-samples#19]
Hello from yesterday I am facing a wired behavior of spring boot projects that whenever I am adding JPA and mysql I am getting build stating "Error creating bean with name". The original error is 

Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException

while executing mvn spring-boot:run

I am clueless how to debug it. Please help me.

**Comment by azanelli** [comment]
Hello, in case of problems and/or questions please use [Stackoverflow](https://stackoverflow.com). Thank you :blush:.
