### ISSUE TITLE
dear netgloo  ,how to solve this problem ?

### ISSUE THREAD

**Issue by damozhiying** [netgloo/spring-boot-samples#4]
User.java

@Entity
@Inheritance(strategy=InheritanceType.JOINED)
@DiscriminatorColumn(name = "user_type")
@Table(name = "users")
public  class User {

  // ==============
  // PRIVATE FIELDS
  // ==============
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user email
  @NotNull
  private String email;
  
  // ==============
  // PUBLIC METHODS
  // ==============
  
  /**
   * @return the id
   */
  public long getId() {
    return id;
  }

  /**
   * @return the email
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param id the id to set
   */
  public void setId(long id) {
    this.id = id;
  }

  /**
   * @param email the email to set
   */
  public void setEmail(String email) {
    this.email = email;
  }

} // class User

in UserRepository.java
@Transactional
public interface UserRepository extends UserBaseRepository<User> { 
	
	//@Query(value="select u from User u where u.email=?1")
	@Query(value="select u.id,u.email from User u where u.email=?1")
	User getUser(String email);
	
	@Query("select u from User u where u.email=?1")
	User getUser2(String email);
	
	@Query(value="select * from Users where email=:email",nativeQuery=true)
	User getUser3(String email);
	
}

there is a exception blew
Hibernate: select user0_.id as col_0_0_, user0_.email as col_1_0_ from users user0_ where user0_.email=?
org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.Object[] to type netgloo.models.User for value '{1, 635@qq.com}'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.lang.Long to type netgloo.models.User

**Comment by azanelli** [comment]
In case of problems and/or questions please use [Stackoverflow](http://stackoverflow.com/). Thank you.
